version: '3.7'

services:
  gistapi:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:9876"
    command: ["gunicorn", "--bind", "0.0.0.0:9876", "--workers", "4", "gistapi:create_app()"]